language: bash
sudo: required
git:
  depth: 1

matrix:
  include:
    - name: Windows (VS2017 64)
      os: windows

before_script:
  - export WINKITS_10=`find "/c/Program Files (x86)/Windows Kits/10" -name rc.exe -printf "%h\n" | grep x64`
  - export VS2017_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023"

  # export path lib and include for VS2017
  # export PATH="$MSBUILD_PATH;"$PATH
  - export PATH="$WINKITS_10;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64;"$PATH
  - export LIB="C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\ATLMFC\lib\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\lib\x64;"
  - export INCLUDE="C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\atlmfc\include;"
  - export INCLUDE="C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include;"$INCLUDE

  - echo $WINKITS_10

  - echo $TRAVIS_OS_NAME

script:
  - echo $PATH
